version: 2

sources:
  - name: dbo
    schema: dbo
    database: spark_catalog
    tables:
      - name: employees
        columns:
          - name: EmpID
            data_type: integer
          - name: FirstName
            data_type: string
          - name: LastName
            data_type: string
          - name: Department
            data_type: string
          - name: Salary
            data_type: decimal(10,2)
          - name: HireDate
            data_type: date

models:
  - name: employees_renamed
    description: "Employee table with renamed columns"
    columns:
      - name: employee_id
        description: "Unique identifier for each employee"
        data_type: integer
      - name: first_name
        data_type: string
      - name: last_name
        data_type: string
      - name: department
        data_type: string
      - name: salary
        data_type: decimal(10,2)
      - name: hire_date
        data_type: date

  - name: employees_transformed
    description: "Employee table with transformed data types and formats"
    columns:
      - name: employee_id
        description: "Unique identifier for each employee (converted to bigint)"
        data_type: bigint
      - name: first_name
        description: "First name in uppercase"
        data_type: string
      - name: last_name
        description: "Last name in uppercase"
        data_type: string
      - name: department
        description: "Department name in proper case"
        data_type: string
      - name: salary
        description: "Salary as double precision"
        data_type: double
      - name: hire_date
        description: "Hire date truncated to month"
        data_type: date
